mSet<-InitDataObjects("pktable", "stat", FALSE)
mSet<-Read.TextData(mSet, "FIB_metaboanalyst_wardD2.csv", "rowu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "NULL", "NULL", "AutoNorm", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 600, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 600, width=NA)
mSet<-FC.Anal.unpaired(mSet, 2.0, 0)
mSet<-PlotFC(mSet, "fc_0_", "png", 600, width=NA)
mSet<-Ttests.Anal(mSet, F, 0.05, FALSE, TRUE, FALSE)
mSet<-PlotTT(mSet, "tt_0_", "png", 600, width=NA)
mSet<-Volcano.Anal(mSet, FALSE, 2.0, 0, 0.75,F, 0.1, TRUE, "raw")
mSet<-PlotVolcano(mSet, "volcano_0_",1, "png", 600, width=NA)
mSet<-PLSR.Anal(mSet, reg=TRUE)
mSet<-PlotPLSPairSummary(mSet, "pls_pair_0_", "png", 600, width=NA, 5)
mSet<-PlotPLS2DScore(mSet, "pls_score2d_0_", "png", 600, width=NA, 1,2,0.95,0,0)
mSet<-PlotPLS3DScoreImg(mSet, "pls_score3d_0_", "png", 600, width=NA, 1,2,3, 40)
mSet<-PlotPLSLoading(mSet, "pls_loading_0_", "png", 600, width=NA, 1, 2);
mSet<-PlotPLS3DLoading(mSet, "pls_loading3d_0_", "json", 1,2,3)
mSet<-PLSDA.CV(mSet, "T",5, "Q2")
mSet<-PlotPLS.Classification(mSet, "pls_cv_0_", "png", 600, width=NA)
mSet<-PlotPLS.Imp(mSet, "pls_imp_0_", "png", 600, width=NA, "vip", "Comp. 1", 15,FALSE)
mSet<-PlotPLSPairSummary(mSet, "pls_pair_0_", "png", 600, width=7, 5)
mSet<-PlotPLS.Imp(mSet, "pls_imp_1_", "png", 600, width=NA, "vip", "Comp. 1", 20,FALSE)
mSet<-PlotPLS.Imp(mSet, "pls_imp_1_", "png", 600, width=7, "vip", "Comp. 1", 20,FALSE)
mSet<-PlotPLS.Imp(mSet, "pls_imp_2_", "png", 600, width=NA, "coef", "Overall", 20,FALSE)
mSet<-PlotPLS.Imp(mSet, "pls_imp_2_", "png", 600, width=7, "coef", "Overall", 20,FALSE)
mSet<-SaveTransformedData(mSet)
